version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth_service
      - user_service
      - team_service

  user_service:
    build:
      context: ./user_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////app/operation.sqlite
      - RABBIT_HOST=rabbitmq
    volumes:
      - ./user_service:/app
      - ./operation.sqlite:/app/operation.sqlite
    env_file:
      - .env
    depends_on:
      - rabbitmq

  auth_service:
    build:
      context: ./auth_service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite:////app/operation.sqlite
      - RABBIT_HOST=rabbitmq
    volumes:
      - ./auth_service:/app
      - ./operation.sqlite:/app/operation.sqlite
    env_file:
      - .env
    depends_on:
      - rabbitmq

  team_service:
    build:
      context: ./team_service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=sqlite:////app/operation.sqlite
      - RABBIT_HOST=rabbitmq
    volumes:
      - ./team_service:/app
      - ./operation.sqlite:/app/operation.sqlite
    env_file:
      - .env
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
